version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8084:80"
      - "445:443"
    volumes:
      - /home/piotr/kanboard/data:/var/www/app/data
      - /home/piotr/kanboard/plugins:/var/www/app/plugins
      - /home/piotr/kanboard/ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
