version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /home/piotr/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
