version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8083:80/tcp"
      - "444:443/tcp"
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: 'jCNcYVTUX240WoHU'
    volumes:
      - '/home/piotr/pihole/pihole:/etc/pihole/'
      - '/home/piotr/pihole/dnsmasq:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
