version: "2"
services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /home/piotr/smokeping/config:/config
      - /home/piotr/smokeping/data:/data
    ports:
      - 8082:80
    restart: unless-stopped
